import test from 'node:test';import assert from 'node:assert/strict';import {contexts,recommend,parseCapture,captureGroups} from './engine.js';
const profile={routine:'출근',days:[1,2,3,4,5],dressCode:1,walking:30,cooling:false,fit:'기본 핏',style:'미니멀'};
const clothes=[{id:'t',category:'top',color:'흰색',fit:'기본 핏',style:'미니멀',formal:1,warmth:1,available:true},{id:'b',category:'bottom',color:'검정',formal:1,warmth:1,available:true},{id:'s',category:'shoe',color:'검정',formal:1,comfort:true,available:true},{id:'s2',category:'shoe',color:'남색',formal:1,comfort:false,available:true}];
test('저녁 약속은 반복 출근을 유지하고 휴가는 해당 반복 활동을 제거한다',()=>{const regular=contexts(profile,'저녁 약속','2026-10-06');assert.equal(regular.routine,'출근');assert.equal(regular.formal,1);assert.equal(contexts(profile,'오늘 휴가, 저녁 약속','2026-10-06').routine,'');assert.equal(contexts(profile,'오늘 재택','2026-10-06').remote,true);});
test('도보 이동은 편한 신발을 선택하며 입을 수 없는 옷은 제외한다',()=>{const c=contexts(profile,'','2026-10-06');const r=recommend(clothes,profile,c,{min:20,max:24});assert.equal(r.outfit.find(i=>i.category==='shoe').id,'s');const unavailable=clothes.map(i=>i.id==='s'?{...i,available:false}:i);const r2=recommend(unavailable,profile,c,{min:20,max:24});assert(!r2.outfit.some(i=>i.id==='s'));assert(r2.notices.some(s=>s.includes('신발')));});
test('조합에 필요한 옷이 없으면 보유하지 않은 옷을 만들지 않는다',()=>{const r=recommend(clothes.filter(i=>i.category!=='bottom'),profile,contexts(profile,''),null);assert.equal(r.outfit,null);assert(r.missing.includes('하의'));});
test('날씨 미확인과 격식 부족을 명시한다',()=>{const r=recommend(clothes,profile,contexts(profile,'면접'),null);assert(r.notices.some(s=>s.includes('날씨')));assert(r.notices.some(s=>s.includes('격식')));});
test('시간대가 기록된 실제 촬영 시각은 UTC로 비교한다',()=>{assert.equal(parseCapture('2026:10:06 10:00:00','+09:00').epoch,parseCapture('2026:10:06 01:00:00','+00:00').epoch);assert.equal(parseCapture('2026:02:30 10:00:00'),null);assert.equal(parseCapture(undefined),null);});
test('촬영 정보 누락, 플래시 변경, 시간대 유무 차이는 같은 묶음으로 확정하지 않는다',()=>{const mk=(id,time,flash=0,offset='+09:00')=>({id,capture:{...parseCapture(time,offset),model:'sample-camera',make:'sample',flash}});const a=mk('a','2026:10:06 09:00:00'),b=mk('b','2026:10:06 09:05:00'),c=mk('c','2026:10:06 09:06:00',1),d=mk('d','2026:10:06 09:07:00',0,null);const groups=captureGroups([a,b,c,d,{id:'missing'}]);assert.equal(groups.length,1);assert.deepEqual(groups[0].map(i=>i.id),['a','b']);});
test('시간 묶음은 첫 사진 기준으로 제한하여 연쇄적으로 하루 전체가 묶이지 않는다',()=>{const items=[0,9,18].map((n,i)=>({id:String(i),capture:{...parseCapture(`2026:10:06 09:${String(n).padStart(2,'0')}:00`,'+09:00'),model:'sample-camera',make:'sample'}}));assert.deepEqual(captureGroups(items)[0].map(i=>i.id),['0','1']);});
test('휴가에는 출근에 연결된 도보·냉방 조건을 제거하고 직접 입력한 이동은 반영한다',()=>{const p={...profile,cooling:true};const holiday=contexts(p,'오늘 휴가, 저녁 약속','2026-10-06');assert.equal(holiday.walking,0);assert.equal(holiday.cooling,false);assert.equal(contexts(p,'오늘 휴가, 도보 이동','2026-10-06').walking,30);});
test('구매 후보 비교에는 후보가 반드시 포함되며 보유 옷으로 둔갑하지 않는다',()=>{const candidate={id:'candidate',candidate:true,category:'outer',color:'베이지',formal:1,warmth:1,available:true};const r=recommend([...clothes,candidate],profile,contexts(profile,''),{min:25,max:30},{requiredId:'candidate'});assert(r.outfit.some(i=>i.id==='candidate'&&i.candidate));assert.equal(clothes.some(i=>i.id==='candidate'),false);});

